# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ghcr.io/acts-project/${{ matrix.image }}:v11
    strategy:
      matrix:
        image:
          - ubuntu2004
          
    # Setup the environment
    env:
      SETUP: true
      INSTALL_DIR: ${{ github.workspace }}/install
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Init the submodule
      - name: Initialise git submodules
        run: git submodule update --init

      # Configure 
      - name: Configure CMake
        run: >
          ${SETUP} &&
          cmake -B build -S acts
          -GNinja
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_CXX_FLAGS=-Werror
          -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}"
          -DACTS_BUILD_EVERYTHING=on
          -DACTS_LOG_FAILURE_THRESHOLD=WARNING
          
      # Build and Install ACTS
      - name: Build ACTS
        run: cmake --build build
